/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package wellknown

type resource struct {
	Names      []string
	Namespaced bool
	Group      string
}

// Don't edit this file directly. It is generated by hack/gen_wellknown_resources
var resources = []resource{
	{
		Names: []string{
			"bindings",
			"binding",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"componentstatuses",
			"componentstatus",
			"cs",
		},
		Namespaced: false,
		Group:      "",
	},
	{
		Names: []string{
			"configmaps",
			"configmap",
			"cm",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"endpoints",
			"ep",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"events",
			"event",
			"ev",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"limitranges",
			"limitrange",
			"limits",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"namespaces",
			"namespace",
			"ns",
		},
		Namespaced: false,
		Group:      "",
	},
	{
		Names: []string{
			"nodes",
			"node",
			"no",
		},
		Namespaced: false,
		Group:      "",
	},
	{
		Names: []string{
			"persistentvolumeclaims",
			"persistentvolumeclaim",
			"pvc",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"persistentvolumes",
			"persistentvolume",
			"pv",
		},
		Namespaced: false,
		Group:      "",
	},
	{
		Names: []string{
			"pods",
			"pod",
			"po",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"podtemplates",
			"podtemplate",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"replicationcontrollers",
			"replicationcontroller",
			"rc",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"resourcequotas",
			"resourcequota",
			"quota",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"secrets",
			"secret",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"serviceaccounts",
			"serviceaccount",
			"sa",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"services",
			"service",
			"svc",
		},
		Namespaced: true,
		Group:      "",
	},
	{
		Names: []string{
			"mutatingwebhookconfigurations",
			"mutatingwebhookconfiguration",
		},
		Namespaced: false,
		Group:      "admissionregistration.k8s.io",
	},
	{
		Names: []string{
			"validatingadmissionpolicies",
			"validatingadmissionpolicy",
		},
		Namespaced: false,
		Group:      "admissionregistration.k8s.io",
	},
	{
		Names: []string{
			"validatingadmissionpolicybindings",
			"validatingadmissionpolicybinding",
		},
		Namespaced: false,
		Group:      "admissionregistration.k8s.io",
	},
	{
		Names: []string{
			"validatingwebhookconfigurations",
			"validatingwebhookconfiguration",
		},
		Namespaced: false,
		Group:      "admissionregistration.k8s.io",
	},
	{
		Names: []string{
			"customresourcedefinitions",
			"customresourcedefinition",
			"crd",
			"crds",
		},
		Namespaced: false,
		Group:      "apiextensions.k8s.io",
	},
	{
		Names: []string{
			"apiservices",
			"apiservice",
		},
		Namespaced: false,
		Group:      "apiregistration.k8s.io",
	},
	{
		Names: []string{
			"controllerrevisions",
			"controllerrevision",
		},
		Namespaced: true,
		Group:      "apps",
	},
	{
		Names: []string{
			"daemonsets",
			"daemonset",
			"ds",
		},
		Namespaced: true,
		Group:      "apps",
	},
	{
		Names: []string{
			"deployments",
			"deployment",
			"deploy",
		},
		Namespaced: true,
		Group:      "apps",
	},
	{
		Names: []string{
			"replicasets",
			"replicaset",
			"rs",
		},
		Namespaced: true,
		Group:      "apps",
	},
	{
		Names: []string{
			"statefulsets",
			"statefulset",
			"sts",
		},
		Namespaced: true,
		Group:      "apps",
	},
	{
		Names: []string{
			"selfsubjectreviews",
			"selfsubjectreview",
		},
		Namespaced: false,
		Group:      "authentication.k8s.io",
	},
	{
		Names: []string{
			"tokenreviews",
			"tokenreview",
		},
		Namespaced: false,
		Group:      "authentication.k8s.io",
	},
	{
		Names: []string{
			"localsubjectaccessreviews",
			"localsubjectaccessreview",
		},
		Namespaced: true,
		Group:      "authorization.k8s.io",
	},
	{
		Names: []string{
			"selfsubjectaccessreviews",
			"selfsubjectaccessreview",
		},
		Namespaced: false,
		Group:      "authorization.k8s.io",
	},
	{
		Names: []string{
			"selfsubjectrulesreviews",
			"selfsubjectrulesreview",
		},
		Namespaced: false,
		Group:      "authorization.k8s.io",
	},
	{
		Names: []string{
			"subjectaccessreviews",
			"subjectaccessreview",
		},
		Namespaced: false,
		Group:      "authorization.k8s.io",
	},
	{
		Names: []string{
			"horizontalpodautoscalers",
			"horizontalpodautoscaler",
			"hpa",
		},
		Namespaced: true,
		Group:      "autoscaling",
	},
	{
		Names: []string{
			"cronjobs",
			"cronjob",
			"cj",
		},
		Namespaced: true,
		Group:      "batch",
	},
	{
		Names: []string{
			"jobs",
			"job",
		},
		Namespaced: true,
		Group:      "batch",
	},
	{
		Names: []string{
			"certificatesigningrequests",
			"certificatesigningrequest",
			"csr",
		},
		Namespaced: false,
		Group:      "certificates.k8s.io",
	},
	{
		Names: []string{
			"leases",
			"lease",
		},
		Namespaced: true,
		Group:      "coordination.k8s.io",
	},
	{
		Names: []string{
			"endpointslices",
			"endpointslice",
		},
		Namespaced: true,
		Group:      "discovery.k8s.io",
	},
	{
		Names: []string{
			"events",
			"event",
			"ev",
		},
		Namespaced: true,
		Group:      "events.k8s.io",
	},
	{
		Names: []string{
			"flowschemas",
			"flowschema",
		},
		Namespaced: false,
		Group:      "flowcontrol.apiserver.k8s.io",
	},
	{
		Names: []string{
			"prioritylevelconfigurations",
			"prioritylevelconfiguration",
		},
		Namespaced: false,
		Group:      "flowcontrol.apiserver.k8s.io",
	},
	{
		Names: []string{
			"ingressclasses",
			"ingressclass",
		},
		Namespaced: false,
		Group:      "networking.k8s.io",
	},
	{
		Names: []string{
			"ingresses",
			"ingress",
			"ing",
		},
		Namespaced: true,
		Group:      "networking.k8s.io",
	},
	{
		Names: []string{
			"networkpolicies",
			"networkpolicy",
			"netpol",
		},
		Namespaced: true,
		Group:      "networking.k8s.io",
	},
	{
		Names: []string{
			"runtimeclasses",
			"runtimeclass",
		},
		Namespaced: false,
		Group:      "node.k8s.io",
	},
	{
		Names: []string{
			"poddisruptionbudgets",
			"poddisruptionbudget",
			"pdb",
		},
		Namespaced: true,
		Group:      "policy",
	},
	{
		Names: []string{
			"clusterrolebindings",
			"clusterrolebinding",
		},
		Namespaced: false,
		Group:      "rbac.authorization.k8s.io",
	},
	{
		Names: []string{
			"clusterroles",
			"clusterrole",
		},
		Namespaced: false,
		Group:      "rbac.authorization.k8s.io",
	},
	{
		Names: []string{
			"rolebindings",
			"rolebinding",
		},
		Namespaced: true,
		Group:      "rbac.authorization.k8s.io",
	},
	{
		Names: []string{
			"roles",
			"role",
		},
		Namespaced: true,
		Group:      "rbac.authorization.k8s.io",
	},
	{
		Names: []string{
			"priorityclasses",
			"priorityclass",
			"pc",
		},
		Namespaced: false,
		Group:      "scheduling.k8s.io",
	},
	{
		Names: []string{
			"csidrivers",
			"csidriver",
		},
		Namespaced: false,
		Group:      "storage.k8s.io",
	},
	{
		Names: []string{
			"csinodes",
			"csinode",
		},
		Namespaced: false,
		Group:      "storage.k8s.io",
	},
	{
		Names: []string{
			"csistoragecapacities",
			"csistoragecapacity",
		},
		Namespaced: true,
		Group:      "storage.k8s.io",
	},
	{
		Names: []string{
			"storageclasses",
			"storageclass",
			"sc",
		},
		Namespaced: false,
		Group:      "storage.k8s.io",
	},
	{
		Names: []string{
			"volumeattachments",
			"volumeattachment",
		},
		Namespaced: false,
		Group:      "storage.k8s.io",
	},
}
