version: "2"
linters:
  default: none
  enable:
    - errorlint
    - importas
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    importas:
      alias:
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
    nakedret:
      max-func-lines: 5
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: early-return
          arguments:
            - preserveScope
        - name: error-return
        - name: error-naming
        - name: error-strings
        - name: errorf
        - name: if-return
        - name: increment-decrement
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
          arguments:
            - preserveScope
        - name: receiver-naming
        - name: redundant-import-alias
        - name: superfluous-else
          arguments:
            - preserveScope
        - name: unnecessary-stmt
        - name: unused-parameter
        - name: use-any
        - name: use-errors-new
        - name: useless-break
        - name: var-declaration
        - name: var-naming
          disabled: true
        - name: exported
          disabled: true
        - name: unexported-return
          disabled: true
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA2002
        - ST1019
    usetesting:
      os-mkdir-temp: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - ineffassign
        path: conversion\.go
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - go.etcd.io
  exclusions:
    generated: lax
    paths:
      - ^zz_generated.*
      - third_party$
      - builtin$
      - examples$
